database:
  host: root:passwd@tcp(localhost:3306)/database

http:
  session_domain: appdomain
  secret: secret

server:
  port: :8080
  appid: appid
  key: secret_key

env:
  mode: debug
  
auth:
  cas: https://domain
